arpit456jain/Amazing-Js-Projects

- Calculators/Calculator3/Calculator3.html
- Calculators/Calculator3/cal3_app.js
- Calculators/Calculator3/cal3_style.css
- To-Do List/app.js
- To-Do List/index.html
- To-Do List/style.css
- style_links.json
added calculator and To-do List
> added js-projects

- Tic-Tac-Toe with computer/app.js
- Tic-Tac-Toe with computer/index.html
- Tic-Tac-Toe with computer/style.css
- style_links.json
> tic-tac-toe added

- Magic Image/index.html
> added height to image

- Weather-App/index.html
- Weather-App/script.js
- Weather-App/style.css
- style_links.json
Added Weather App
Weather App #14
- [ ✔️] New feature (non-breaking change which adds functionality)
- Operating system: Windows 
- Version: 10
- Text-editors used: VS Code
- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have performed a self-review of my own code
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [✔️ ] I have made corresponding changes to the documentation
- [✔️ ] My changes generate no new warnings
- [✔️ ] I have added tests that prove my fix is effective or that my feature works
- [✔️ ] New and existing unit tests pass locally with my changes
- [ ✔️] Any dependent changes have been merged and published in downstream modules
> Weather App

- .github/workflows/Auto_message_on_creatingissues.yml
- .github/workflows/Auto_message_on_pr_merge.yml
- .github/workflows/greetings.yml
form link added
Fixes #17 
- Version:
> form link added

- CONTRIBUTORS.md
Add Contributing guidelines
Fixes #19
> Add Contributing guidelines

- CONTRIBUTORS.md
- README.md
> add points table in read me

- style_links.json
Added Missing Projects
#12 (Add remaining templates in style_link.json #12)
- Operating system:Windows
- Version:10
- Text-editors used: VS Code
> Added Missing Projects

- README.md
Added the GitHub pages website link to the Readme file of this repository. 
Fixes #35
> Added GitHub pages website link to Readme

- .github/ISSUE_TEMPLATE/Bug_Feature_Docs.md
- README.md
Now the issue template works as intended and works properly.
Fixes #42
> Corrected the Issue Template

- Snake Game/index.html
- Snake Game/script.js
- Snake Game/style.css
Add Score on main screen
Rename speed as level
Snake Game #75
- Version:
> Snake Game 

- README.md
- Uploaded the recording gif to the repository.
- Added a homepage preview gif recording to the README file.
- Added it to the Demo section 
Fixes #78 
- Operating system: Windows 10
- Version:
> Added homepage gif to README

- Weather-App/index.html
Just added an icon to the weather app. Please tell me whether you would like me to add icons for the other projects too. Thanks (:
> Added icon to the Weather App

- calculatorspage.html
- index.html
> Add two more items in navbar with links

- Snake Game/index.html
- Snake Game/script.js
- Snake Game/style.css
I had modified Snake Game, now it display MaxScore, It use no external dependencies.
Fixes # 77
Feature Introduce
- Operating system: MAC OS
- Version: 10.15.7
- Text-editors used: visual studio code
> added max score, enter to reset the game functionality in Snake Game

- randomColorGenerator/index.html
- randomColorGenerator/index.js
- randomColorGenerator/style.css
Added a simple javascript project for generating random colors.
- Version:
> added a basic javascript for generating random colors

- Pong game/index.html
Pong is a table tennis-themed arcade sports video game, featuring simple two-dimensional graphics
#hacktoberfest
> Add pong game

- BMI-Calculator/index.css
- BMI-Calculator/index.html
- BMI-Calculator/main.js
I had Added BMI Calculator
To find out BMI we will take input from the user (both height and weight) which will be stored in height and weight variables for further calculation
Fixes (#166 )
> Added BMI Calculator

- Palindrome Check/script.js
This code will now clear the input field and displays the past value result.
I have simplify the script.js by reducing the space complexity and introduced a new feature which will clear the input field and display the previous results along with their the input attached to that result.
Fixes #193 
- Operating system: Windows
- Version:10 Home
- Text-editors used:VS code editor
> Optimized Palindrome Check

- Blury Loading Page/index.css
- Blury Loading Page/index.html
- Blury Loading Page/index.js
Hey @arpit456jain 
I added an Image with a blur filter over it.
Have a look and merge in your repo or give back any feedback.
> Added Blurry Loading 

- Notes Maker/index.html
- Notes Maker/script.js
- Notes Maker/style.css
In this NotesMaker app, users can make their notes (that includes the heading of topic and description), and also they can delete their previous notes.
Fixes #196
> Added NotesMaker App

- color-guessing game/index.html
- color-guessing game/java/main.js
- color-guessing game/styles.css
#Description
This is a color guessing game having two levels easy and hard. On clicking new color every time, a random color gets generated which has to be guessed among the options. The options are 3(in easy) and 6(in hard).
If wrong color is chosen, that particular box disappears and the total-wrong options chosen would remain. If the right color is chosen all the boxes change their color to the right color.
Fixes # 194
Issue no: #194 
- Version:
> I am a GSSOC participant . I have added new project : color guessing game

- Fresh Quotes/index.html
- Fresh Quotes/style.css
I add new js project fresh quotes 
you click on new quotes button then show new quotes....
- Operating system: window 
- Version:10
- Text-editors used:vs code
> i add new js project Fresh Quotes 2

- Text_to_speech_converter/index.html
- Text_to_speech_converter/main.js
- Text_to_speech_converter/styles.css
This is a Text to speech converter. In this,anything written in the textarea will be converted into speech of the chosen language. 
Fixes #223 
Issue no #223 
- Version:
> added text to speech converter

- Age Calculator/index.html
- Age Calculator/script.js
- Age Calculator/style.css
> Added Age Calculator

- index.html
- style.css
In the footer, I add About, other projects with working links and social icons that didn't work because we don't have pages right now so I give a green hover effect to look good & last added Copyright
Fixes #237 
- Operating system: Windows 11
- Version: 21H2
- Text-editors used: VS Code
> Footer added

- style.css
> Update hover effect in Navbar

- README.md
Added gssoc 2022 and added mentors section below project admins
Added gssoc 2022 and added mentors section below project admins
> updated README.md (#1)

- BaseX_Calculator/app.js
- BaseX_Calculator/index.html
- BaseX_Calculator/readme.md
- BaseX_Calculator/style.css
Added BaseX Calculator files. The project allows to change from & to any desired base such as: `` Decimal to Binary ``, `` Binary to Octal ``, `` Base 3 to Base 6 ``, ..etc.
Fixes #268 
- Operating system: Windows, Linux
- Version: 10, Ubuntu
- Text-editors used: Sublime
https://user-images.githubusercontent.com/64689436/156848560-6f763520-5a6c-4aeb-8c3d-1f7ebc5db2e5.mp4
> Added BaseX Calculator files

- Image Filter App/index.html
This closes Bug report: Image Filter App
work done:changed classname typo from "fliter-btn" to "filter-btn"  on line no 32, 40, 48, 57
For: with the above typo, 4 functions: brightness, contrast, saturation & vibrance were increasing, but not decreasing.
Fixes #299  (issue no.)
fixed typo "fliter-btn" which was causing disability to lower brightness, contrast, saturation & vibrance of the given image file.
- Version:
> Updated typo "fliter-btn" in index.html file

- style.css
> Adding the scrollbar

- Birthday Countdown/script.js
- Birthday Countdown/style.css
there was a bug in  in birthday countdown that that year was a particular year ,so countdown shows no dates, I generalized  it , So that , you do not have to change it every year. 
fixes #316
> birthday-countdown-bug #316

- PIng _Pong _Ball _Score_Keeper/app.js
- PIng _Pong _Ball _Score_Keeper/index.html
- PIng _Pong _Ball _Score_Keeper/style.css
Added files for the project ping pong ball score keeper.
#294 
VS Code
<image src="https://user-images.githubusercontent.com/82977727/124570137-39a2d280-de64-11eb-852d-8281d6149c58.png"> Counting Scores </image>
<image src="https://user-images.githubusercontent.com/82977727/124570624-b170fd00-de64-11eb-90aa-810a07848ec7.png"> </image>
> Added Ping Pong Ball Score Keeper

- Transpose-3X3-Matrix Calculator/README.md
- Transpose-3X3-Matrix Calculator/index.html
- Transpose-3X3-Matrix Calculator/script.js
- Transpose-3X3-Matrix Calculator/style.css
I have added Transpose of 3X3 Matrix Calculator which calculates the transpose of a 3X3 matrix.  The user needs to input a 3x3 matrix and the Calculator displays its transpose matrix in very few seconds.
This is built with- HTML,CSS and JavaScript. It is responsive and supports all devices.
Fixes #328
- Operating system: Windows
- Version: 10
- Text-editors used: VS Code
> Transpose of 3X3 Matrix Calculator #328

- color-change/app.js
- color-change/index.html
- color-change/styles.css
A Simple fun game which changes background color after refreshing each time.
Fixes # (issue no.)#314
- Operating system: Windows
- Version : 11
- Text-editors used:Visual Studio Code
> Color-Change

- Color_Code_Converter/app.js
- Color_Code_Converter/index.html
- Color_Code_Converter/readme.md
- Color_Code_Converter/style.css
A color code converter that converts between RGB, Hex, CMYK & Hsl.
- Conversion from any of the supported formats: RGB, Hex, CMYK, & Hsl.
- User input is validated using Regex.
Fixes #288 
- Operating system: Linux, Windows
- Version: Ubuntu, 10
- Text-editors used: Sublime
> Added ColorCode Converter project files

- Background Color Changer/index.html
- Background Color Changer/script.js
- Background Color Changer/style.css
You can see on sceenshot also, that I have added 8 colors instead of four ,they are no more colors,  they became beautiful linear-gradients, Similarly I made Blog post Heading animated ,  Heading's color will automatically change and cause glow effect  as well .
Fixes #323
- [y ] New feature (non-breaking change which adds functionality)
- Version:
- [y] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my own code
- [y ] I have commented my code, particularly in hard-to-understand areas
- [y ] My changes generate no new warnings
Before Change screenshot
d and published in downstream modules
After changes Screenshot
> background-Changer-Modification

- Flipbook/README.md
- Flipbook/index.html
- Flipbook/script.js
- Flipbook/style.css
- Flipbook/turn.js
Added a responsive flipbook project
Fixes #347
> #347 issue fixed

- style_links.json
I have made the required changes
Fixes #358 
- Operating system: ANY
- Version: N/A
- Text-editors used: N/A
> Added changes to the file to sort projects

- index.html
- script.js
- style.css
Added SearchBar, Responsiveness and changed UI of cards components
Fixes #324 
- Version:
> Added SearchBar, Responsiveness and changed UI of cards components

- number_system_convertor/numbersystem.css
- number_system_convertor/numbersystem.js
- number_system_convertor/numbersysystem.html
In this website user can input a binary number and convert into various number system.
#355
- Version: 1.0
- Text-editors used: Vs code
> Number system convertor

- Typewriter effect/app.js
- Typewriter effect/index.html
- Typewriter effect/style.css
Added a new project.
- Version:
> Added a project which uses vanilla javascript to create a type writing effect in a webpage.

- calculatorspage.html
- calculatorspage.js
- index.html
- script.js
- style.css
made new design and added few feature and remove static code.
Fixes #398 
- Version:
> new Design plus Features

- style.css
Horizontal scroll in mobile view is now fixed. now website is completely mobile responsive
Fixes:  #422
> Horizontal Scroll Fixed

- Game-of-pong/CSS/style.css
- Game-of-pong/JS/script.js
- Game-of-pong/Readme.md
- Game-of-pong/index.html
- style_links.json
**Checklist:**
I have made this from my own
I have taken help from some online resourses
My code follows the style guidelines of this project
I have performed a self-review of my own code
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
My changes generate no new warnings
**Description** 
=> I have added the solution to issue #459 
=> by below the image you can see what the game looks like.
=> point are changing dynamically.
=> one player playing with the computer.
**Photos**
> Add game of pong

- Hangman Game/index.html
- Hangman Game/readme.md
- style_links.json
The hangman game is about guessing a random word by guessing letters one by one. If the player runs out of guesses, the game is over.
The solution:
Set a maximum limit for guesses.
Display the remaining number of guesses to the player.
Provide the player with an interface to input their guesses.
Fixes: #496
> Hangman Game

- Random Wave/index.html
- Random Wave/script.js
- Random Wave/style.css
PR - #502
Hey I made random wave project Which Is Very Good!
This Project is very Helpfull,
I Make This Project With the help of HTML, CSS & JavaScript,
The CSS & JavaScript Code are Available in very well mannered! & Easy to understand!
> Adding random wave project

- ToDo App/css/style.css
- ToDo App/index.html
- ToDo App/js/index.js
I Build Todo app using html-css-javascript
Issue number:  #534
> Added Todo app

- .github/workflows/pr-open-labeler.yml
Added action for labeling pull requests
Fixes:  #532
> Added file in workflow

- README.md
> Update README.md and testing bot

- Reflex Training/Index.html
- Reflex Training/Reflex.js
- Reflex Training/Styles.css
- style_links.json
I have added the Reflex Training Game with JS and HTML to the repo.
Fixes:  #525 
closes #525
> Added Reflex Training Game 

- Magic Color/index.html
Improved magic color website.
Increased fonts in mobile view and added title in the website.
Fixes:  #670
> Improved Magic color website

- Clock And Alarm/calendar.css
- Clock And Alarm/index.html
- Clock And Alarm/js/alarm.js
- Clock And Alarm/js/calendar.js
- Clock And Alarm/js/clock.js
- Clock And Alarm/style.css
- Removed bootstrap: Use of bootstrap for just a few classes was a overkill hence removed it.
- Major Changes in the design: mobile responsive too
- Fix new bug:  Fixed-> On selecting January the calendar didn't change which is not the expected behavior.
Fixes:  #668 
- ![image](https://user-images.githubusercontent.com/74536497/169588586-e96ec0d1-a7e2-42f2-bab4-a58c4f367d36.png)
- ![image](https://user-images.githubusercontent.com/74536497/169588647-bbbe3d10-e3f6-4829-998f-6d04670fe12b.png)
- ![image](https://user-images.githubusercontent.com/74536497/169588789-2ed0e4df-f323-4b7c-a66f-dedb4ab61575.png)
> FIX: issue668 and "click on january is buggy"

- Analog clock/index.html
- Analog clock/main.css
- Analog clock/main.js
> Fix: Issue665

- Bubble Burst Game/index.html
- Bubble Burst Game/script.js
Made Bubble Burst Game responsive and increase the size of bubbles
Fixes:  #667
> Solved issue #667 . Made Bubble Burst Game responsive and increase the size of bubbles

- Feedback slider/index.html
- Feedback slider/script.js
- Feedback slider/style.css
Completely fixed the and reworked responsiveness fix for Feedback Slider
Fixes:  #682 
https://user-images.githubusercontent.com/82874704/169712065-a7b9e6b2-6b51-4078-affd-32928fe32985.mp4
> Completely fixed the responsiveness of the slider from Feedback Slider

- README.md
Removed the mentors section and also removed ankita from admins
Fixes:  #(issue no.)
#736 
>README update
> Removed the mentors section and also ren=moved ankita from admins
